import React, { useState } from 'react';
import axios from 'axios';
import { 
  FileText, 
  Download, 
  Sparkles, 
  AlertTriangle, 
  CheckCircle,
  TrendingUp,
  Shield,
  Target,
  Clock,
  Users
} from 'lucide-react';

const Reports = () => {
  const [simulations, setSimulations] = useState([]);
  const [selectedSimulation, setSelectedSimulation] = useState(null);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);

  React.useEffect(() => {
    fetchSimulations();
  }, []);

  const fetchSimulations = async () => {
    try {
      setLoading(true);
      const response = await axios.get('/api/simulations');
      const completed = response.data.simulations.filter(
        s => s.status === 'completed' || s.status === 'stopped'
      );
      setSimulations(completed);
      setLoading(false);
    } catch (error) {
      console.error('Error fetching simulations:', error);
      setLoading(false);
    }
  };

  const generateReport = async (simulationId) => {
    try {
      setGenerating(true);
      setReport(null);
      const response = await axios.post(`/api/reports/generate/${simulationId}`);
      setReport(response.data.report);
      setGenerating(false);
    } catch (error) {
      console.error('Error generating report:', error);
      alert('Error generating report: ' + error.response?.data?.error);
      setGenerating(false);
    }
  };

  const downloadReport = () => {
    if (!report) return;
    
    const reportText = formatReportForDownload(report);
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ransomware-simulation-report-${report.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const formatReportForDownload = (report) => {
    let text = '═══════════════════════════════════════════════════════════\n';
    text += '         RANSOMWARE SIMULATION REPORT\n';
    text += '═══════════════════════════════════════════════════════════\n\n';
    text += `Report ID: ${report.id}\n`;
    text += `Generated: ${new Date(report.generatedAt).toLocaleString()}\n`;
    text += `Generated By: ${report.generatedBy}\n`;
    text += `AI Generated: ${report.aiGenerated ? 'Yes' : 'No'}\n\n`;
    
    text += '───────────────────────────────────────────────────────────\n';
    text += 'EXECUTIVE SUMMARY\n';
    text += '───────────────────────────────────────────────────────────\n\n';
    text += `${report.executiveSummary.overview}\n\n`;
    text += 'Key Findings:\n';
    report.executiveSummary.keyFindings.forEach(f => text += `• ${f}\n`);
    text += '\nCritical Insights:\n';
    report.executiveSummary.criticalInsights.forEach(i => text += `• ${i}\n`);
    text += '\nImmediate Actions:\n';
    report.executiveSummary.immediateActions.forEach(a => text += `• ${a}\n`);
    
    text += '\n───────────────────────────────────────────────────────────\n';
    text += 'ATTACK ANALYSIS\n';
    text += '───────────────────────────────────────────────────────────\n\n';
    text += `Malware Type: ${report.attackAnalysis.malwareType}\n`;
    text += `Severity: ${report.attackAnalysis.severity}\n`;
    text += `Attack Vector: ${report.attackAnalysis.attackVector}\n`;
    text += `Targeted Systems: ${report.attackAnalysis.targetedSystems}\n`;
    text += `Affected Departments: ${report.attackAnalysis.affectedDepartments.join(', ')}\n\n`;
    text += 'Behaviors:\n';
    report.attackAnalysis.behaviors.forEach(b => text += `• ${b}\n`);
    
    text += '\n───────────────────────────────────────────────────────────\n';
    text += 'IMPACT ASSESSMENT\n';
    text += '───────────────────────────────────────────────────────────\n\n';
    text += `Risk Level: ${report.impactAssessment.businessImpact.level}\n`;
    text += `Risk Score: ${report.impactAssessment.businessImpact.score}/100\n`;
    text += `${report.impactAssessment.businessImpact.description}\n\n`;
    text += `Systems Affected: ${report.impactAssessment.technicalImpact.systemsAffected}\n`;
    text += `Data at Risk: ${report.impactAssessment.technicalImpact.dataAtRisk}\n`;
    text += `Estimated Downtime: ${report.impactAssessment.operationalImpact.estimatedDowntime}\n`;
    text += `Recovery Time: ${report.impactAssessment.operationalImpact.recoveryTime}\n`;
    text += `Estimated Cost: ${report.impactAssessment.financialImpact.estimatedCost}\n`;
    
    text += '\n───────────────────────────────────────────────────────────\n';
    text += 'DETECTION GAPS\n';
    text += '───────────────────────────────────────────────────────────\n\n';
    if (report.detectionGaps.length > 0) {
      report.detectionGaps.forEach(gap => {
        text += `[${gap.severity}] ${gap.category}\n`;
        text += `  ${gap.description}\n`;
        text += `  Recommendation: ${gap.recommendation}\n\n`;
      });
    } else {
      text += 'No significant detection gaps identified.\n\n';
    }
    
    text += '───────────────────────────────────────────────────────────\n';
    text += 'RECOMMENDATIONS\n';
    text += '───────────────────────────────────────────────────────────\n\n';
    text += 'Immediate (0-7 days):\n';
    report.recommendations.immediate.forEach(r => text += `• ${r}\n`);
    text += '\nShort-term (1-3 months):\n';
    report.recommendations.shortTerm.forEach(r => text += `• ${r}\n`);
    text += '\nLong-term (3-12 months):\n';
    report.recommendations.longTerm.forEach(r => text += `• ${r}\n`);
    
    text += '\n───────────────────────────────────────────────────────────\n';
    text += 'NEXT STEPS\n';
    text += '───────────────────────────────────────────────────────────\n\n';
    report.nextSteps.forEach(step => {
      text += `Priority ${step.priority}: ${step.action}\n`;
      text += `  Owner: ${step.owner}\n`;
      text += `  Timeline: ${step.timeline}\n\n`;
    });
    
    text += '═══════════════════════════════════════════════════════════\n';
    text += '                    END OF REPORT\n';
    text += '═══════════════════════════════════════════════════════════\n';
    
    return text;
  };

  const getRiskColor = (level) => {
    switch (level?.toLowerCase()) {
      case 'critical': return 'text-red-600 bg-red-100 border-red-200';
      case 'high': return 'text-orange-600 bg-orange-100 border-orange-200';
      case 'medium': return 'text-yellow-600 bg-yellow-100 border-yellow-200';
      default: return 'text-blue-600 bg-blue-100 border-blue-200';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-red-600"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">AI-Generated Reports</h1>
          <p className="text-gray-600 mt-1">Comprehensive analysis of simulation results</p>
        </div>
        <div className="flex items-center space-x-2 px-4 py-2 bg-purple-50 border border-purple-200 rounded-lg">
          <Sparkles className="w-5 h-5 text-purple-600" />
          <span className="text-sm text-purple-800 font-medium">AI-Powered Analysis</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Simulation List */}
        <div className="lg:col-span-1">
          <div className="card">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Select Simulation</h3>
            <div className="space-y-2 max-h-[600px] overflow-y-auto">
              {simulations.map((sim) => (
                <div
                  key={sim.id}
                  onClick={() => {
                    setSelectedSimulation(sim);
                    generateReport(sim.id);
                  }}
                  className={`p-3 border-2 rounded-lg cursor-pointer transition-all ${
                    selectedSimulation?.id === sim.id
                      ? 'border-purple-600 bg-purple-50'
                      : 'border-gray-200 hover:border-gray-300'
                  }`}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <p className="font-medium text-gray-900 text-sm">{sim.malware?.name}</p>
                      <p className="text-xs text-gray-600 mt-1">
                        {new Date(sim.createdAt).toLocaleDateString()}
                      </p>
                      <p className="text-xs text-gray-500 mt-1">
                        {sim.targetHosts?.length} hosts
                      </p>
                    </div>
                    {selectedSimulation?.id === sim.id && (
                      <CheckCircle className="w-5 h-5 text-purple-600" />
                    )}
                  </div>
                </div>
              ))}
              {simulations.length === 0 && (
                <div className="text-center py-8 text-gray-500">
                  <FileText className="w-12 h-12 mx-auto mb-2 text-gray-400" />
                  <p className="text-sm">No completed simulations</p>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Report Display */}
        <div className="lg:col-span-2">
          {generating ? (
            <div className="card text-center py-12">
              <Sparkles className="w-12 h-12 text-purple-600 mx-auto mb-4 animate-pulse" />
              <p className="text-lg font-semibold text-gray-900">Generating AI Report...</p>
              <p className="text-sm text-gray-600 mt-2">Analyzing simulation data and generating insights</p>
            </div>
          ) : report ? (
            <div className="space-y-6">
              {/* Report Header */}
              <div className="card">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h2 className="text-2xl font-bold text-gray-900">Simulation Report</h2>
                    <p className="text-sm text-gray-600 mt-1">
                      Generated: {new Date(report.generatedAt).toLocaleString()}
                    </p>
                    <p className="text-sm text-gray-600">
                      By: {report.generatedBy}
                    </p>
                  </div>
                  <button
                    onClick={downloadReport}
                    className="btn btn-primary flex items-center"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </button>
                </div>

                {/* Risk Score */}
                <div className={`p-4 rounded-lg border-2 ${getRiskColor(report.impactAssessment?.businessImpact?.level)}`}>
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium">Overall Risk Level</p>
                      <p className="text-2xl font-bold mt-1">
                        {report.impactAssessment?.businessImpact?.level}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-medium">Risk Score</p>
                      <p className="text-2xl font-bold mt-1">
                        {report.impactAssessment?.businessImpact?.score}/100
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="card">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <FileText className="w-5 h-5 mr-2 text-purple-600" />
                  Executive Summary
                </h3>
                <p className="text-gray-700 mb-4">{report.executiveSummary?.overview}</p>
                
                <div className="space-y-3">
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">Key Findings</h4>
                    <ul className="space-y-1">
                      {report.executiveSummary?.keyFindings?.map((finding, idx) => (
                        <li key={idx} className="text-sm text-gray-700 flex items-start">
                          <span className="text-purple-600 mr-2">•</span>
                          {finding}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">Critical Insights</h4>
                    <ul className="space-y-1">
                      {report.executiveSummary?.criticalInsights?.map((insight, idx) => (
                        <li key={idx} className="text-sm text-gray-700 flex items-start">
                          <span className="text-purple-600 mr-2">•</span>
                          {insight}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>

              {/* Attack Analysis */}
              <div className="card">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <Target className="w-5 h-5 mr-2 text-red-600" />
                  Attack Analysis
                </h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-gray-600">Malware Type</p>
                    <p className="font-medium text-gray-900">{report.attackAnalysis?.malwareType}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Severity</p>
                    <p className="font-medium text-gray-900">{report.attackAnalysis?.severity}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Targeted Systems</p>
                    <p className="font-medium text-gray-900">{report.attackAnalysis?.targetedSystems}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Departments</p>
                    <p className="font-medium text-gray-900">
                      {report.attackAnalysis?.affectedDepartments?.join(', ')}
                    </p>
                  </div>
                </div>
                <div className="mt-4">
                  <p className="text-sm text-gray-600 mb-2">Observed Behaviors</p>
                  <div className="flex flex-wrap gap-2">
                    {report.attackAnalysis?.behaviors?.map((behavior, idx) => (
                      <span key={idx} className="px-2 py-1 bg-red-100 text-red-800 rounded text-xs">
                        {behavior}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Impact Assessment */}
              <div className="card">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <TrendingUp className="w-5 h-5 mr-2 text-orange-600" />
                  Impact Assessment
                </h3>
                <p className="text-gray-700 mb-4">
                  {report.impactAssessment?.businessImpact?.description}
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-3 bg-gray-50 rounded-lg">
                    <p className="text-sm text-gray-600">Data at Risk</p>
                    <p className="font-medium text-gray-900">
                      {report.impactAssessment?.technicalImpact?.dataAtRisk}
                    </p>
                  </div>
                  <div className="p-3 bg-gray-50 rounded-lg">
                    <p className="text-sm text-gray-600">Estimated Downtime</p>
                    <p className="font-medium text-gray-900">
                      {report.impactAssessment?.operationalImpact?.estimatedDowntime}
                    </p>
                  </div>
                  <div className="p-3 bg-gray-50 rounded-lg">
                    <p className="text-sm text-gray-600">Recovery Time</p>
                    <p className="font-medium text-gray-900">
                      {report.impactAssessment?.operationalImpact?.recoveryTime}
                    </p>
                  </div>
                  <div className="p-3 bg-gray-50 rounded-lg">
                    <p className="text-sm text-gray-600">Estimated Cost</p>
                    <p className="font-medium text-gray-900">
                      {report.impactAssessment?.financialImpact?.estimatedCost}
                    </p>
                  </div>
                </div>
              </div>

              {/* Detection Gaps */}
              {report.detectionGaps && report.detectionGaps.length > 0 && (
                <div className="card">
                  <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                    <AlertTriangle className="w-5 h-5 mr-2 text-yellow-600" />
                    Detection Gaps
                  </h3>
                  <div className="space-y-3">
                    {report.detectionGaps.map((gap, idx) => (
                      <div key={idx} className="p-3 border border-gray-200 rounded-lg">
                        <div className="flex items-start justify-between mb-2">
                          <p className="font-medium text-gray-900">{gap.category}</p>
                          <span className={`px-2 py-1 rounded text-xs font-semibold ${
                            gap.severity === 'Critical' ? 'bg-red-100 text-red-800' :
                            gap.severity === 'High' ? 'bg-orange-100 text-orange-800' :
                            'bg-yellow-100 text-yellow-800'
                          }`}>
                            {gap.severity}
                          </span>
                        </div>
                        <p className="text-sm text-gray-700 mb-2">{gap.description}</p>
                        <p className="text-sm text-blue-700">
                          <strong>Recommendation:</strong> {gap.recommendation}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Recommendations */}
              <div className="card">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <Shield className="w-5 h-5 mr-2 text-green-600" />
                  Recommendations
                </h3>
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2 flex items-center">
                      <Clock className="w-4 h-4 mr-2 text-red-600" />
                      Immediate (0-7 days)
                    </h4>
                    <ul className="space-y-1">
                      {report.recommendations?.immediate?.map((rec, idx) => (
                        <li key={idx} className="text-sm text-gray-700 flex items-start">
                          <span className="text-red-600 mr-2">•</span>
                          {rec}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2 flex items-center">
                      <Clock className="w-4 h-4 mr-2 text-orange-600" />
                      Short-term (1-3 months)
                    </h4>
                    <ul className="space-y-1">
                      {report.recommendations?.shortTerm?.map((rec, idx) => (
                        <li key={idx} className="text-sm text-gray-700 flex items-start">
                          <span className="text-orange-600 mr-2">•</span>
                          {rec}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2 flex items-center">
                      <Clock className="w-4 h-4 mr-2 text-blue-600" />
                      Long-term (3-12 months)
                    </h4>
                    <ul className="space-y-1">
                      {report.recommendations?.longTerm?.map((rec, idx) => (
                        <li key={idx} className="text-sm text-gray-700 flex items-start">
                          <span className="text-blue-600 mr-2">•</span>
                          {rec}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>

              {/* Next Steps */}
              <div className="card">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <Users className="w-5 h-5 mr-2 text-purple-600" />
                  Next Steps
                </h3>
                <div className="space-y-3">
                  {report.nextSteps?.map((step, idx) => (
                    <div key={idx} className="p-3 bg-gray-50 rounded-lg">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center mb-1">
                            <span className="px-2 py-1 bg-purple-600 text-white rounded text-xs font-semibold mr-2">
                              Priority {step.priority}
                            </span>
                            <p className="font-medium text-gray-900">{step.action}</p>
                          </div>
                          <p className="text-sm text-gray-600">Owner: {step.owner}</p>
                          <p className="text-sm text-gray-600">Timeline: {step.timeline}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <div className="card text-center py-12">
              <Sparkles className="w-12 h-12 text-gray-400 mx-auto mb-4" />
              <p className="text-gray-600">Select a simulation to generate an AI report</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Reports;
